"""
Module: 'fs_driver' on micropython-v1.27.0-esp32-ESP32_GENERIC_S3-SPIRAM_OCT
"""

# MCU: {'variant': 'SPIRAM_OCT', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3-SPIRAM_OCT', 'mpy': 'v6.3', 'ver': '1.27.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.27.0'}
# Stubber: v1.29.0
from __future__ import annotations

from _typeshed import Incomplete

def _fs_read_cb(*args, **kwargs) -> Incomplete: ...
def _fs_open_cb(*args, **kwargs) -> Incomplete: ...
def _fs_write_cb(*args, **kwargs) -> Incomplete: ...
def _fs_seek_cb(*args, **kwargs) -> Incomplete: ...
def _fs_tell_cb(*args, **kwargs) -> Incomplete: ...
def _fs_close_cb(*args, **kwargs) -> Incomplete: ...
def fs_register(*args, **kwargs) -> Incomplete: ...
def _fs_dir_read_cb(*args, **kwargs) -> Incomplete: ...
def _fs_dir_close_cb(*args, **kwargs) -> Incomplete: ...
def _fs_dir_open_cb(*args, **kwargs) -> Incomplete: ...
